ignore-interior-mutability = [
        "mergiraf::ast::AstNode", "crate::ast::AstNode", "crate::AstNode", "mergiraf::AstNode",
        "mergiraf::ast::AstNode<'_>", "crate::ast::AstNode<'_>", "crate::AstNode<'_>", "mergiraf::AstNode<'_>",
        "&mergiraf::ast::AstNode<'_>", "&crate::ast::AstNode<'_>", "&crate::AstNode<'_>", "&mergiraf::AstNode<'_>",
        "mergiraf_ast::AstNode"
]
