on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: my-ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Install Rust
        uses: https://code.forgejo.org/msrd0/rust-toolchain@stable
        id: rust-toolchain
        with:
          components: clippy, rustfmt
      - name: Cache build dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target            
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}}"
      - name: Format
        run: cargo fmt --all -- --check
      - name: Lint
        run: cargo clippy --all-targets -- -Dwarnings
      - name: Run tests
        run: cargo test --all-features
