on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  rustfmt:
    runs-on: my-ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: https://code.forgejo.org/msrd0/rust-toolchain@stable
        id: rust-toolchain
        with:
          components: rustfmt
      - run: cargo fmt --all -- --check

  clippy:
    runs-on: my-ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: https://code.forgejo.org/msrd0/rust-toolchain@stable
        id: rust-toolchain
        with:
          components: clippy
      - name: Cache build dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target            
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}}"
      - run: cargo clippy --all-targets

  test:
    runs-on: my-ubuntu-22.04
    steps:
      - name: Check out repository
        uses: https://github.com/actions/checkout@v4
      - name: Install Rust
        uses: https://code.forgejo.org/msrd0/rust-toolchain@stable
        id: rust-toolchain
      - name: Cache build dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/git
            ~/.cargo/registry
            target            
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}}"
      - name: Run tests
        run: cargo test --all-features
