on:
  push:
    tags: 'v*'

env:
  CROSS_DOCKER_IN_DOCKER: true # for cross-compilation via the 'cross' tool

jobs:
  release:
    runs-on: ubuntu-with-rust-1.89 # uses Docker image https://hub.docker.com/r/pintoch/ubuntu-act-with-rust
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # for changelog generation
          $fetch-tags: true # for changelog generation
      - name: Cache build dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: "${{runner.os}} Rust ${{steps.rust-toolchain.outputs.cachekey}} lock ${{ hashFiles('**/Cargo.lock') }}"
      - name: Install cross
        run: cargo binstall cross
      - name: Run tests
        run: cargo test --workspace --locked
      - name: Create release artifacts dir and generate release notes
        run: |
          mkdir target/release_artifacts
          # store the release notes into $RELEASE_NOTES
          {
            echo 'RELEASE_NOTES<<EOF'
            git-cliff --latest
            echo EOF
          } >> "$GITHUB_ENV"
      - name: Fix the hostname to reflect the docker container id
        # This is necessary for 'cross' to work in Forgejo Actions.
        # See https://github.com/cross-rs/cross/issues/1351#issuecomment-3476670997
        # and https://code.forgejo.org/forgejo/forgejo-actions-feature-requests/issues/66
        run: echo HOSTNAME=$(docker container ls -q) >> "$GITHUB_ENV"
      - name: Build for all architectures
        run: |
          for arch in $(cat .forgejo/workflows/targets.txt); do
            echo "Building for ${arch}"
            cross build --target ${arch} --release
            cd target/${arch}/release
            if [[ ${arch} == "x86_64-pc-windows-gnu" ]]; then
              zip -r ../../release_artifacts/mergiraf_${arch}.zip mergiraf.exe
            else
              tar -zcv mergiraf -f ../../release_artifacts/mergiraf_${arch}.tar.gz
            fi
            cd ../../..
          done
        env:
          CROSS_CONFIG: .forgejo/workflows/Cross.toml
      - name: Create release
        uses: https://code.forgejo.org/actions/forgejo-release@v2.7.3
        with:
          direction: upload
          url: https://codeberg.org
          repo: mergiraf/mergiraf
          token: ${{ secrets.CODEBERG_WRITE_TOKEN }}
          tag: "${{ github.ref_name }}"
          sha: "${{ github.sha }}"
          release-dir: ./target/release_artifacts
          # read the release notes from $RELEASE_NOTES
          release-notes: ${{ env.RELEASE_NOTES }}
          override: true
      - name: Login on crates.io
        run: echo "${{ secrets.CRATES_IO_API_TOKEN }}" | cargo login
      - name: Publish on crates.io
        run: cargo publish
